name: CI/CD Learn

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code.
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: ./client
      
      - name: Build
        run: npm run build
        working-directory: ./client/build

      - name: AWS CLI Version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version
      
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            /home/runner/work/AI6-Project1/AI6-Project1/client/build s3://final-hyen-project1 \
            --delete
        working-directory: ./client/build
        
